Insert into manufacturers (name,is_active) values ('Sun Pharmaceutical Industries',TRUE);
Insert into manufacturers (name,is_active) values ('Serum Institute of India',TRUE);
Insert into manufacturers (name,is_active) values ('Systopic Laboratories',TRUE);
Insert into manufacturers (name,is_active) values ('Mankind Pharma',TRUE);
Insert into manufacturers (name,is_active) values ('Dr. Reddys Laboratories',TRUE);
Insert into manufacturers (name,is_active) values ('Abbott India',TRUE);
Insert into manufacturers (name,is_active) values ('Skn Organics Pvt Ltd',TRUE);
Insert into manufacturers (name,is_active) values ('Indoco Remedies Ltd',TRUE);
Insert into manufacturers (name,is_active) values ('Biomiicron Pharma India',TRUE);
Insert into manufacturers (name,is_active) values ('P&G Health (Procter & Gamble)',TRUE);
Insert into manufacturers (name,is_active) values ('Alkem Laboratories',TRUE);
Insert into manufacturers (name,is_active) values ('Stadmed Pvt Ltd',TRUE);
Insert into manufacturers (name,is_active) values ('Cipla Limited',TRUE);
Insert into manufacturers (name,is_active) values ('USV Private Limited',TRUE);
Insert into manufacturers (name,is_active) values ('Sapient Laboratories',TRUE);
Insert into manufacturers (name,is_active) values ('Corona Remedies Pvt Ltd',TRUE);
Insert into manufacturers (name,is_active) values ('Lupin Ltd',TRUE);
Insert into manufacturers (name,is_active) values ('Zuventus Healthcare Ltd',TRUE);
Insert into manufacturers (name,is_active) values ('Pharmed Ltd',TRUE);
Insert into manufacturers (name,is_active) values ('Golgi USA Research Labs',TRUE);
Insert into manufacturers (name,is_active) values ('Glenmark Pharmaceuticals',TRUE);
Insert into manufacturers (name,is_active) values ('Eris Lifesciences Ltd',TRUE);
Insert into manufacturers (name,is_active) values ('Apex Laboratories Pvt Ltd',TRUE);
Insert into manufacturers (name,is_active) values ('HBC Lifesciences Pvt Ltd',TRUE);
Insert into manufacturers (name,is_active) values ('Charak Pharma',TRUE);
Insert into manufacturers (name,is_active) values ('Wallace Pharmaceuticals',TRUE);
Insert into manufacturers (name,is_active) values ('Fourrts India Laboratories',TRUE);
