-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.patient_identifier
(
    id integer NOT NULL,
    id_name character varying NOT NULL,
    is_active boolean,
    PRIMARY KEY (id, id_name)
);

CREATE TABLE IF NOT EXISTS public.patient_services
(
    id integer NOT NULL,
    service_name character varying NOT NULL,
    is_active boolean,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.payment_mode
(
    id integer NOT NULL,
    mode character varying NOT NULL,
    is_active boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.patient_payment
(
    id integer NOT NULL,
    patient_name character varying NOT NULL,
    payment_date date NOT NULL,
    total_amount double precision NOT NULL DEFAULT 0.00,
    gst_amout double precision DEFAULT 0.00,
    notes character varying,
    created_by integer NOT NULL,
    created_date time with time zone NOT NULL,
    modified_by integer NOT NULL,
    modified_date time with time zone NOT NULL,
    free_flag boolean NOT NULL DEFAULT false,
    token_no integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ptnt_pymnt_x_ptnt_id
(
    id integer NOT NULL,
    patient integer,
    id_value character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    username character varying COLLATE pg_catalog."default" NOT NULL,
    email character varying COLLATE pg_catalog."default" NOT NULL,
    hashed_password character varying COLLATE pg_catalog."default" NOT NULL,
    is_active boolean,
    created_at timestamp without time zone,
    status_id integer DEFAULT 1,
    role character varying COLLATE pg_catalog."default" DEFAULT 'Staff'::character varying,
    CONSTRAINT users_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ptnt_pmnt_x_ptnt_srvcs
(
    id integer NOT NULL,
    patient integer,
    services integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.ptnt_pmnt_srvcs_x_value
(
    id integer NOT NULL,
    services integer,
    mode integer,
    value double precision,
    notes character varying,
    modified_by integer NOT NULL,
    modified_date timestamp with time zone NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.patient_payment
    ADD CONSTRAINT "create" FOREIGN KEY (created_by, modified_by)
    REFERENCES public.users (id, id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.ptnt_pymnt_x_ptnt_id
    ADD CONSTRAINT id FOREIGN KEY (id)
    REFERENCES public.patient_identifier (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.ptnt_pymnt_x_ptnt_id
    ADD FOREIGN KEY (patient)
    REFERENCES public.patient_payment (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.ptnt_pmnt_x_ptnt_srvcs
    ADD FOREIGN KEY (patient, services)
    REFERENCES public.patient_payment (id, id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.ptnt_pmnt_srvcs_x_value
    ADD FOREIGN KEY (services)
    REFERENCES public.ptnt_pmnt_x_ptnt_srvcs (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.ptnt_pmnt_srvcs_x_value
    ADD FOREIGN KEY (mode)
    REFERENCES public.payment_mode (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.ptnt_pmnt_srvcs_x_value
    ADD FOREIGN KEY (modified_by)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;