INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Sun Pharmaceutical Industries', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Serum Institute of India', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Systopic Laboratories', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Mankind Pharma', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Dr. Reddys Laboratories', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Abbott India', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Skn Organics Pvt Ltd', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Indoco Remedies Ltd', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Biomiicron Pharma India', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('P&G Health (Procter & Gamble)', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Alkem Laboratories', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Stadmed Pvt Ltd', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Cipla Limited', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('USV Private Limited', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Sapient Laboratories', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Corona Remedies Pvt Ltd', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Lupin Ltd', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Zuventus Healthcare Ltd', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Pharmed Ltd', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Golgi USA Research Labs', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Glenmark Pharmaceuticals', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Eris Lifesciences Ltd', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Apex Laboratories Pvt Ltd', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('HBC Lifesciences Pvt Ltd', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Charak Pharma', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Wallace Pharmaceuticals', NULL, NULL, NULL, NULL, TRUE);
INSERT INTO manufacturers (name, address, contact_person, contact_email, phone_number, is_active) VALUES ('Fourrts India Laboratories', NULL, NULL, NULL, NULL, TRUE);