-- 1. Setup the custom Medicine Category ENUM
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'medicinecategory') THEN
        CREATE TYPE medicinecategory AS ENUM (
            'GENERAL', 'OTC', 'SCHEDULE_H', 'SCHEDULE_H1', 'SCHEDULE_X'
        );
    END IF;
END $$;

-- 2. Create the Medicines Table
CREATE TABLE IF NOT EXISTS medicines (
    id SERIAL PRIMARY KEY,
    product_name CHARACTER VARYING NOT NULL,
    generic_name CHARACTER VARYING,
    description CHARACTER VARYING,
    unit_price DOUBLE PRECISION,
    manufacturer_id INTEGER REFERENCES manufacturers(id),
    hsn_code CHARACTER VARYING(8),
    category medicinecategory,
    uom CHARACTER VARYING,
    storage_type CHARACTER VARYING,
    is_active BOOLEAN,
    selling_price_percent DOUBLE PRECISION
);

-- 3. Individual Insert Statements for better reliability
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Calcidef Tablet', 'Calcium + Folic Acid + Vitamin D2', 'Calcium + Folic Acid + Vitamin D2 + Glycine', 120.00, (SELECT id FROM manufacturers WHERE name = 'Sun Pharmaceutical Industries'), '30049099', 'GENERAL', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Febutaz 40 mg Tablet', 'Febuxostat', 'Febuxostat [for Uric Acid/Gout]', 165.50, (SELECT id FROM manufacturers WHERE name = 'Sun Pharmaceutical Industries'), '30049099', 'SCHEDULE_H', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Strone Capsule', 'Progesterone', 'Progesterone [Hormonal supplement]', 350.00, (SELECT id FROM manufacturers WHERE name = 'Serum Institute of India'), '30043919', 'SCHEDULE_H', 'Strip', 'Controlled', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Sysfol-Activ Capsule', 'L-Methylfolate + Mecobalamin', 'L-Methylfolate + Mecobalamin + Pyridoxal-5-Phosphate', 190.00, (SELECT id FROM manufacturers WHERE name = 'Systopic Laboratories'), '30049099', 'GENERAL', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Mahacef 200 Tablet', 'Cefixime', 'Cefixime [Antibiotic]', 105.00, (SELECT id FROM manufacturers WHERE name = 'Mankind Pharma'), '30042019', 'SCHEDULE_H1', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Omez 20 Capsule', 'Omeprazole', 'Omeprazole [Antacid/Acidity]', 55.00, (SELECT id FROM manufacturers WHERE name = 'Dr. Reddys Laboratories'), '30049099', 'OTC', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Flagyl 400 Tablet', 'Metronidazole', 'Metronidazole [Antibiotic/Anti-amoebic]', 22.40, (SELECT id FROM manufacturers WHERE name = 'Abbott India'), '30049099', 'SCHEDULE_H', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('SK Fer Softgel', 'Ferrous Ascorbate + Folic Acid', 'Ferrous Ascorbate + Folic Acid + Methylcobalamin', 145.00, (SELECT id FROM manufacturers WHERE name = 'Skn Organics Pvt Ltd'), '30049099', 'GENERAL', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Meprate 10 mg Tablet', 'Medroxyprogesterone Acetate', 'Medroxyprogesterone Acetate [Hormonal]', 65.00, (SELECT id FROM manufacturers WHERE name = 'Serum Institute of India'), '30043919', 'SCHEDULE_H', 'Strip', 'Controlled', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Nosic 10mg/10mg Tablet', 'Doxylamine + Pyridoxine', 'Doxylamine + Pyridoxine [Pregnancy Nausea]', 110.00, (SELECT id FROM manufacturers WHERE name = 'Indoco Remedies Ltd'), '30049099', 'SCHEDULE_H', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Mensil-N CR 10 Tablet', 'Norethisterone', 'Norethisterone [for Period irregularities]', 180.00, (SELECT id FROM manufacturers WHERE name = 'Biomiicron Pharma India'), '30043919', 'SCHEDULE_H', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Evion 400 Capsule', 'Vitamin E', 'Vitamin E [Nutritional supplement]', 35.00, (SELECT id FROM manufacturers WHERE name = 'P&G Health (Procter & Gamble)'), '30045020', 'OTC', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Pan 40 Tablet', 'Pantoprazole', 'Pantoprazole [Antacid/Acidity]', 145.00, (SELECT id FROM manufacturers WHERE name = 'Alkem Laboratories'), '30049099', 'SCHEDULE_H', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Urisol 200 mg Tablet', 'Flavoxate', 'Flavoxate [Urinary Antispasmodic]', 210.00, (SELECT id FROM manufacturers WHERE name = 'Stadmed Pvt Ltd'), '30049099', 'SCHEDULE_H', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Urifur 100 mg Tablet SR', 'Nitrofurantoin', 'Nitrofurantoin [UTI Antibiotic]', 115.00, (SELECT id FROM manufacturers WHERE name = 'Cipla Limited'), '30049099', 'SCHEDULE_H1', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Glycomet 500 mg Tablet', 'Metformin', 'Metformin [Anti-diabetic]', 18.00, (SELECT id FROM manufacturers WHERE name = 'USV Private Limited'), '30049099', 'SCHEDULE_H', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Omez-D Capsule', 'Omeprazole + Domperidone', 'Omeprazole + Domperidone', 140.00, (SELECT id FROM manufacturers WHERE name = 'Dr. Reddys Laboratories'), '30049099', 'SCHEDULE_H', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Drosi Kare Tablet', 'Drospirenone + Ethinyl Estradiol', 'Drospirenone + Ethinyl Estradiol [Contraceptive]', 490.00, (SELECT id FROM manufacturers WHERE name = 'Mankind Pharma'), '30066010', 'SCHEDULE_H', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Dydroboon 10 mg Tablet', 'Dydrogesterone', 'Dydrogesterone [Hormonal]', 550.00, (SELECT id FROM manufacturers WHERE name = 'Mankind Pharma'), '30043919', 'SCHEDULE_H', 'Strip', 'Controlled', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Stimucor 5 mg Tablet', 'Letrozole', 'Letrozole [Infertility/Anovulation]', 125.00, (SELECT id FROM manufacturers WHERE name = 'Sapient Laboratories'), '30049099', 'SCHEDULE_H', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Argihope 1000 mg Tablet', 'L-Arginine', 'L-Arginine [Amino Acid]', 240.00, (SELECT id FROM manufacturers WHERE name = 'Corona Remedies Pvt Ltd'), '30049099', 'GENERAL', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Tasika MF Tablet', 'Tranexamic Acid + Mefenamic Acid', 'Tranexamic Acid + Mefenamic Acid [Heavy Periods]', 210.00, (SELECT id FROM manufacturers WHERE name = 'Lupin Ltd'), '30049099', 'SCHEDULE_H', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Zuvilix 200 mg Tablet', 'Elagolix', 'Elagolix [for Endometriosis]', 950.00, (SELECT id FROM manufacturers WHERE name = 'Zuventus Healthcare Ltd'), '30049099', 'SCHEDULE_H', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Supracal Tablet', 'Calcium Citrate + Vitamin D3', 'Calcium Citrate + Vitamin D3 + Minerals', 130.00, (SELECT id FROM manufacturers WHERE name = 'Pharmed Ltd'), '30049099', 'GENERAL', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Zuviston Tablet', 'Dydrogesterone', 'Dydrogesterone [Hormonal]', 550.00, (SELECT id FROM manufacturers WHERE name = 'Zuventus Healthcare Ltd'), '30043919', 'SCHEDULE_H', 'Strip', 'Controlled', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Multiod LC Tab', 'Multivitamin + Benfotiamine', 'Multivitamin + Benfotiamine + Levocarnitine', 195.00, (SELECT id FROM manufacturers WHERE name = 'Golgi USA Research Labs'), '30045020', 'GENERAL', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Candid-D Ointment', 'Clotrimazole + Dexamethasone', 'Clotrimazole + Dexamethasone [Antifungal]', 85.00, (SELECT id FROM manufacturers WHERE name = 'Glenmark Pharmaceuticals'), '30043200', 'SCHEDULE_H', 'Each', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Cyclopam Tablet', 'Dicyclomine + Paracetamol', 'Dicyclomine + Paracetamol [Antispasmodic]', 45.00, (SELECT id FROM manufacturers WHERE name = 'Indoco Remedies Ltd'), '30049099', 'SCHEDULE_H', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Ecosprin 75/150', 'Aspirin', 'Aspirin [Blood Thinner]', 10.50, (SELECT id FROM manufacturers WHERE name = 'USV Private Limited'), '30049099', 'SCHEDULE_H', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Cynomycin 100 Capsule', 'Minocycline', 'Minocycline [Antibiotic]', 280.00, (SELECT id FROM manufacturers WHERE name = 'Sun Pharmaceutical Industries'), '30042019', 'SCHEDULE_H1', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('VH 3 Vaginal Suppository', 'Clindamycin + Clotrimazole', 'Clindamycin + Clotrimazole', 160.00, (SELECT id FROM manufacturers WHERE name = 'Systopic Laboratories'), '30049099', 'SCHEDULE_H', 'Each', 'Cold Chain (2-8°C)', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Sysfol 5 mg Tablet', 'Folic Acid', 'Folic Acid [Vitamin B9]', 30.00, (SELECT id FROM manufacturers WHERE name = 'Systopic Laboratories'), '30049099', 'GENERAL', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Metital Tablet', 'Metformin + Myo-Inositol', 'Metformin + Myo-Inositol [for PCOS]', 220.00, (SELECT id FROM manufacturers WHERE name = 'Eris Lifesciences Ltd'), '30049099', 'SCHEDULE_H', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Vomikind 4 mg Tablet', 'Ondansetron', 'Ondansetron [Anti-emetic]', 38.00, (SELECT id FROM manufacturers WHERE name = 'Mankind Pharma'), '30049099', 'SCHEDULE_H', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Reluease Tablet', 'Relugolix + Estradiol', 'Relugolix + Estradiol + Norethindrone', 1200.00, (SELECT id FROM manufacturers WHERE name = 'Sun Pharmaceutical Industries'), '30043919', 'SCHEDULE_H', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Evazeal SR Tablet', 'Progesterone', 'Progesterone [Sustained Release]', 320.00, (SELECT id FROM manufacturers WHERE name = 'Apex Laboratories Pvt Ltd'), '30043919', 'SCHEDULE_H', 'Strip', 'Controlled', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Pan IV Injection', 'Pantoprazole', 'Pantoprazole [Injection form]', 48.00, (SELECT id FROM manufacturers WHERE name = 'Alkem Laboratories'), '30049099', 'SCHEDULE_H', 'Vial', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Xone 1g Injection', 'Ceftriaxone', 'Ceftriaxone [Antibiotic Injection]', 155.00, (SELECT id FROM manufacturers WHERE name = 'Alkem Laboratories'), '30042019', 'SCHEDULE_H1', 'Vial', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Emeset 4 mg Tablet', 'Ondansetron', 'Ondansetron [Anti-nausea]', 40.00, (SELECT id FROM manufacturers WHERE name = 'Cipla Limited'), '30049099', 'SCHEDULE_H', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Neurobion Forte', 'Vitamin B Complex', 'Vitamin B Complex [B1, B6, B12]', 32.00, (SELECT id FROM manufacturers WHERE name = 'P&G Health (Procter & Gamble)'), '30045020', 'GENERAL', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Mymifer Tablet', 'Ferrous Ascorbate + Folic Acid', 'Ferrous Ascorbate + Folic Acid + Zinc', 160.00, (SELECT id FROM manufacturers WHERE name = 'HBC Lifesciences Pvt Ltd'), '30049099', 'GENERAL', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('M2-Tone Tablet/Syrup', 'Ayurvedic Herbs', 'Ayurvedic Formulation [Charak Pharma]', 135.00, (SELECT id FROM manufacturers WHERE name = 'Charak Pharma'), '30049011', 'GENERAL', 'Bottle', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Diovol Forte Tablet', 'Antacid Mixture', 'Antacid [Aluminium + Magnesium + Dimethicone]', 15.00, (SELECT id FROM manufacturers WHERE name = 'Wallace Pharmaceuticals'), '30049099', 'OTC', 'Strip', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Sucrafil Suspension', 'Sucralfate', 'Sucralfate [for Gastric Ulcers]', 215.00, (SELECT id FROM manufacturers WHERE name = 'Fourrts India Laboratories'), '30049099', 'SCHEDULE_H', 'Bottle', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Mupon Ointment', 'Mupirocin', 'Mupirocin 2% [Topical Antibiotic]', 110.00, (SELECT id FROM manufacturers WHERE name = 'Glenmark Pharmaceuticals'), '30042019', 'SCHEDULE_H', 'Each', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Duphalac Syrup', 'Lactulose', 'Lactulose [Laxative]', 285.00, (SELECT id FROM manufacturers WHERE name = 'Abbott India'), '30049099', 'GENERAL', 'Bottle', 'Ambient', TRUE, 5.0);
INSERT INTO medicines (product_name, generic_name, description, unit_price, manufacturer_id, hsn_code, category, uom, storage_type, is_active, selling_price_percent) VALUES ('Florita Capsule', 'Lactobacillus', 'Probiotic [Lactobacillus for Vaginal Health]', 240.00, (SELECT id FROM manufacturers WHERE name = 'Sun Pharmaceutical Industries'), '30049099', 'GENERAL', 'Strip', 'Cold Chain (2-8°C)', TRUE, 5.0);